### PR TITLE
Removed unused code that caused compilation errors.

### PR DESCRIPTION
**Pull request by ffatheranderson**
Was not able to compile the project with that deprecated code existed. :) THank you for your work on moving project to maven. I was going to do the same, but you have already done it. Please share your email or discord, or mention some other ways to contact you in your profile in github.

### CODE REVIEW

**Comment by ffatheranderson** [comment]
It would be nice to provide with some feedback about reasons you closed this PR.

**Comment by yanlyub** [comment]
> It would be nice to provide with some feedback about reasons you closed this PR.
> @yanlyub

Sorry I have just now seen this PR against my PR, didn't even know that this is possible. I have not closed your PR manually, my own PR was accepted and merged into vassal's master, and I deleted this PR's branch, this is what must have closed your PR.

There should not be any compilation errors due to the code that you removed, also we cannot simply remove deprecated code as we do not know for sure whether it is still used by some modules. Right now it is a lengthy process to determine which deprecated code parts exactly are still in use by modules, and not everyone can initiate this process as it has to run in the filesystem where all the module files are saved.

Again, sorry for not having seen this PR earlier, I haven't expected to see any PR's into my PR and must have overlooked it somehow. You are welcome to partake in Vassal's development, do a PR against https://github.com/vassalengine/vassal and we will have a look and decide what to do with it!

**Comment by yanlyub** [comment]
@ffatheranderson if you are looking for ways to contribute - an easy and very useful way to start contributing is to have a look at the compilation warnings and to fix them step by step. Also, look at https://github.com/vassalengine/vassal/pull/26, once that one is merged we will have several thousand warnings from checkstyle, these will need to be fixed.

**Comment by ffatheranderson** [comment]
Got it. :) Will keep that in mind. @yanlyub do you speak Russian?

**Comment by yanlyub** [comment]
Sure! Russian, english, german, bit of french, bit spanish.

**Pull request closed without merging**
